### ISSUE TITLE
React 1.6 support

### ISSUE THREAD

**Issue by aogaili** [huytbt/react-read-more#4]
Hello,

I'm facing several issues when using this package with react 16.

1. PropTypes are no longer included in the react package
2. If I fix the PropTypes issue, I run into the following error:

```
 Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
	 in span (created by Truncate)
	 in Truncate (created by ReadMore)
         ....
```

Thank you!

**Comment by or2008** [comment]
facing the same issue.. 
@aliogaili did you solve it, or find a workaround?

**Comment by huytbt** [comment]
Thank for your report issue @aliogaili @or2008.
I will update this soon.

**Comment by aogaili** [comment]
@or2008 sorry for the response, I actually didn't find any read-more library that worked well with links so I just resorted to having a vertical scroll.

But I think this one was the closed to the ideal solution so I hope @huytbt resolve this issue.
