### ISSUE TITLE
Uncaught TypeError: Cannot read property 'node' of undefined

### ISSUE THREAD

**Issue by riazXrazor** [huytbt/react-read-more#7]
## This seems to be an error coz if `PropTypes` i'm not sure though
Truncate.js:346 Uncaught TypeError: Cannot read property 'node' of undefined
    at eval (Truncate.js:346)
    at Object.697 (registration-specification.js:1502)
    at __webpack_require__ (registration-specification.js:20)
    at eval (index.js:8)
    at Object.1056 (registration-specification.js:169)
    at __webpack_require__ (registration-specification.js:20)
    at eval (index.jsx:41)
    at Object.1052 (registration-specification.js:137)
    at __webpack_require__ (registration-specification.js:20)
    at registration-specification.js:63

**Comment by yasserzubair** [comment]
you are probably using react 16. This occurs because proptypes have been deprecated in react 16.

**Comment by arximughal** [comment]
How do we overcome this? Is there an upgraded version without `PropTypes`, that would solve this issue?

**Comment by emanueloliveira23** [comment]
React documentation recommends use of [prop-types](https://www.npmjs.com/package/prop-types) package. This module must update to use prop-types.

**Comment by juanferreira** [comment]
I just made a pull request addressing this. See #8 .

**Comment by Rahulv2492** [comment]
I am still getting above issue.

Prototype is still declared in old style.

Truncate.propTypes = {
  children: _react.PropTypes.node,
  ellipsis: _react.PropTypes.node,
  lines: _react.PropTypes.oneOfType([_react.PropTypes.oneOf([false]), _react.PropTypes.number]),
  options: _react.PropTypes.object,
  onTruncate: _react.PropTypes.func
};
